---
title: "12 Updates and Issues"
output: html_document
date: "2026-01-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Updates and news

* Version 0.8.1: More fluorophores, rearranging detectors if needed
* Version 0.8.2: Support for Mosaic and Xenith cytometers
* Version 0.8.3: Patch for error introduced in 0.8.2
* Version 0.8.4: Changes to error messaging in check.control.file
* Version 0.8.5: Improvements to keyword handling in writing FCS files
* Version 0.8.6: Improvements to plotting, fluorophore matching
* Version 0.8.7: Support for Symphony A5 SE and Cytek Northern Lights. More improvements to plotting. Marker names will now be added to the control file based on matches in the FCS file names, where possible. The Hotspot(TM) matrix will be calculated and plotted as per the [preprint](https://www.biorxiv.org/content/10.1101/2025.04.17.649396v2.full.pdf) by Peter Mage et al.
* Version 0.9.0: 
  - Changes to `get.spectral.variants`, including fixing of previously user-modifiable parameters, low-level denoising of spectra and a bug patch for situations with beads using internal negatives. 
  - More checks in `check.control.file`. 
  - New parallel backend. 
  - Faster AutoSpectral unmixing in base R. 
  - Adjustments to reduce any discontinuities produced during unmixing.
  - See also updates in `AutoSpectralRcpp`, including a large speed up and general improvement to the Poisson IRLS unmixing.
  - Patch to `reload.flow.control` bug affecting ID7000 samples.
  - Patch to `define.flow.control()` affecting universal negative definitions and 
impacting on `clean.controls()`.
  - Calculation of the unmixing matrix (Moore-Penrose pseudoinverse) will now be
done using singular value decomposition `svd()` for numerical stability for all
approaches. Up to now, it has been done with normal equations via `solve()`.
This should be better in edge cases. In most cases, the only difference will be
floating point error. Calculation time is equivalent because almost all of the
computational effort is on projecting the raw data into the unmixed space via
the unmixing matrix, not calculating the unmixing matrix.
  - New functions to `save.unmixing.matrix` and `calculate.weights`
  - Patches to `define.flow.control` that were causing redundant gates to be created.
  - Code legibility formatting.
* Version 0.9.1:
 - Switch to `FlowSOM::SOM()` from `EmbedSOM::SOM()`.
 - Patch to appending "-A" suffix to parameter names.
* Version 0.9.2:
 - Faster base R per-cell optimization.
 - Patch to writing of "-A" in the channel names of FCS files. 
 

* Version 1.0.0: 
 - Changes to `unmix.autospectral()` to speed up processing and reduce discontinuities in the resulting unmixed data.

